// lib/core/services/firebase_options.dart
// ⚠️  THIS FILE IS AUTO-GENERATED by FlutterFire CLI.
// ⚠️  DO NOT EDIT MANUALLY.
//
// This is a placeholder. The real file will be generated when you run:
//   flutterfire configure
// after completing the Firebase Console setup steps.
//
// For now this file allows the code to compile without error.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web platform not configured');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError('iOS not configured yet');
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  // ──────────────────────────────────────────────────────────────────────────
  // REPLACE ALL VALUES BELOW after running: flutterfire configure
  // ──────────────────────────────────────────────────────────────────────────
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: 'REPLACE_WITH_YOUR_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_STORAGE_BUCKET',
  );
}
